### ISSUE TITLE
Send key combination

### ISSUE THREAD

**Issue by stevland** [DaviPtrs/hass-unified-remote#22]
remote_id: Relmtech.Keyboard
action: toggle
extras:
  Values:
    - Value: CONTROL

Is there a way to send two keys (let's say, CONTROL + 1) as a combination? Or each in quick succession?

**Comment by stevland** [comment]
I found the solution for this.

Using UnifiedRemote's CustomKeys functionality I created a remote called VolumeControls. The key combinations I need to send are invoked by that remote.

Here's how I created the new remote.

`C:\ProgramData\Unified Remote\Remotes\Custom\Stevland\meta.prop`

```
meta.name: Volume Controls
meta.author: Stevland
meta.description: MediaPC
meta.tags: volume
```

`C:\ProgramData\Unified Remote\Remotes\Custom\Stevland\layout.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<layout>
	<row>
		<button text="🡸" ontap="PanLeft" />
	</row>
</layout>
```

`C:\ProgramData\Unified Remote\Remotes\Custom\Stevland\remote`

```
local kb = libs.keyboard;

--@help PanLeft
actions.PanLeft = function ()
	kb.stroke("ctrl", "left");
end
```

My Volume Controls remote now shows up 

- in the UnifiedRemote app
- in the web GUI
- and I can call it within Home Assistant using hass-unified-remote like so:

```
tap_action:
  action: call-service
  service: unified_remote.call
  service_data:
    target: 192.168.2.17
    remote_id: Stevland.VolumeControls
    action: PanLeft
```

See [https://www.unifiedremote.com/tutorials/how-to-create-a-custom-keyboard-shortcuts-remote](https://www.unifiedremote.com/tutorials/how-to-create-a-custom-keyboard-shortcuts-remote) for more info.
