### ISSUE TITLE
Support for templates

### ISSUE THREAD

**Issue by Kraechtshammer** [DaviPtrs/hass-unified-remote#23]
Hi,
Unless I'm doing things awfully wrong, it seems like the Value field doesn't accept templates? It would be great if it did! 

Just to check that this is not a case of pebcak, here's my plan/usecase:
I've been playing around with a button that is an input_number with minutes as unit. Holding will open the more-info card to change value. Tapping the button should call the power shutdown service with the input_number * 60 so I'm able to schedule a shutdown eg when downloading something over night. (I confirmed that this works with hardcoded numbers). But it doesn't work. This is the service data I'm using (sry about the cringy host name):
```
target: battlestation
remote: power
action: shutdown
extras:
  Values:
    - Value: "{{ states('input_number.shutdown_timer_value') | int * 60 }}"
```
 Am I doing this wrong or does it not work and this can be implemented?
